# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fyp2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fyp2
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'fyp2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fyp2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fyp2-tvOS

  target 'fyp2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
